### ISSUE TITLE
Stripe Web - stripeAccountId

### ISSUE THREAD

**Issue by deepthi-bhattachar** [flutter-stripe/flutter_stripe#1042]
**Describe the bug**
Stripe Stripe.instance.confirmPayment fails in Chrome Web when Stripe account id is added.

POST: /v1/payment_intents/pi_3M8A7YBAguNJNaT202kt83vu/confirm
Status: 404
{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such payment_intent: 'pi_3M8A7YBAguNJNaT202kt83vu'",
    "param": "intent",
    "request_log_url": "",
    "type": "invalid_request_error"
  }
}

**To Reproduce**

if(state is PageInitStateEvent){
      WidgetsFlutterBinding.ensureInitialized();
      Stripe.publishableKey = stripePublishableKey;
      Stripe.merchantIdentifier = stripeMerchant;
      Stripe.stripeAccountId = stripeAccountId;
      await Stripe.instance.applySettings();
    }

await Stripe.instance.confirmPayment(
          _bloc.payment_intent, paymentMethodParams,
        ).then((paymentIntent) =>
        ({
          if(paymentIntent.status == PaymentIntentsStatus.Succeeded){
            navigator.popBack(context: context),
            _bloc.paymentStatus = PaymentStatusTag.success,
            _bloc.dispatchEvent(OnPayPaymentCompleteEvent(_bloc.order_id)),
          } else {
              _bloc.paymentStatus = PaymentStatusTag.failed,
            setState(() {
              _bloc.paymentCompleted = true;
            })
            }
        })).catchError((error) => {
          if (error != null){
            _bloc.paymentStatus = PaymentStatusTag.failed,
            setState(() {
              _bloc.paymentCompleted = true;
            }),
          }
        });

 

Same code is working as expected in iOS, please help. 

**Expected behavior**
Payment to be successful in Chrome browser as in iOS

**Smartphone / tablet**
 - Device: Web Chrome

**Additional context**

flutter_stripe: ^7.0.0
flutter_stripe_web: ^2.0.1

dependency_overrides:
  stripe_platform_interface: ^7.0.0

Flutter version: 
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (3 days ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

**Comment by jamesblasco** [comment]
Was this PaymentIntent was created in the server with a Connected account attached to it?

**Comment by deepthi-bhattachar** [comment]
Sorry for late reply.

Yes, PaymentIntent was created in the server with connected account. Same code works for iOS but fails in web.

**Comment by deepthi-bhattachar** [comment]
@jamesblasco - Wanted to follow-up regarding this issue. As of now I have hardcoded stripeAccountId in SDK and is working. However this is not very helpful since AccountId should be dynamic. I have highlighted the changes which I have made.

@override
  Future<void> initialise({
    required String publishableKey,
    String? stripeAccountId,
    ThreeDSecureConfigurationParams? threeDSecureParams,
    String? merchantIdentifier,
    String? urlScheme,
    bool? setReturnUrlSchemeOnAndroid,
  }) async {
    await stripe_js.loadStripe();
    if (__stripe != null) return;
    final stripeOption = stripe_js.StripeOptions();
    if (stripeAccountId != null) {
      stripeOption.stripeAccount = stripeAccountId;
    }
    **stripeOption.stripeAccount = "acct_1124....";**

    __stripe = stripe_js.Stripe(publishableKey, stripeOption);
    this.urlScheme = urlScheme;
  }

  static stripe_js.StripeElement? element;
  static stripe_js.StripeElements? elements;

  @override
  Future<PaymentMethod> createPaymentMethod(
    PaymentMethodParams data, [
    PaymentMethodOptions? options,
  ]) async {
    **final type = data.toJson()['paymentMethodType'];**
    switch (type) {
      case 'Card':
        return createCardPaymentMethod(data, {});
      case 'Alipay':
        return createCardPaymentMethod(data, {});
    }

    throw UnimplementedError();
  }

**Comment by jamesblasco** [comment]
This should now work with the latest release as requested, please let me know if you encounter any issues

**Comment by michaelaboah** [comment]
I've run into this issue, where the 'Stripe-Account' header is missing from the request. I've been trying to find where in the code the stripeAccountId gets passed to the `confirmPaymentIntent()` but I've had no luck. Even when calling `await Stripe.instance.applySettings()` nothing seems to change

**Comment by kunambi** [comment]
> I've run into this issue, where the 'Stripe-Account' header is missing from the request. I've been trying to find where in the code the stripeAccountId gets passed to the `confirmPaymentIntent()` but I've had no luck. Even when calling `await Stripe.instance.applySettings()` nothing seems to change

Hi @michaelaboah did you manage to solve this issue?

**Comment by EdHourani** [comment]
This is still an issue. Web doesn't allow you to change stripeAccountId to allow for payments to multiple Connected Accounts

On web you cant change the Stripe.stripeAccountId after calling Stripe.instance.applySettings()
Requests that are sent out don't have _stripe_account if you don't set it before Stripe.instance.applySettings() unless you set Stripe.stripeAccountId before calling Stripe.instance.applySettings(). and if you do, you cant change that value or clear it

Works fine on ios/ android

<details>
<summary>Minimum reproducible example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Stripe.publishableKey = 'stripePublishableKey';

  // Stripe.stripeAccountId = 'connectedAccountId';
  await Stripe.instance.applySettings();
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              const CardField(),
              TextButton(
                onPressed: () async {
                  await _createPaymentMethod(null);
                },
                child: const Text('Pay for something from platform'),
              ),
              TextButton(
                onPressed: () async {
                  await _createPaymentMethod('connectedAccountId');
                },
                child: const Text('Pay for something from a connected account'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future _createPaymentMethod(String? connectedAccountId) async {
    Stripe.stripeAccountId = connectedAccountId;
    Stripe.instance.applySettings();
    await Stripe.instance.createPaymentMethod(
      params: const PaymentMethodParams.card(
        paymentMethodData: PaymentMethodData(),
      ),
    );
  }
}

```
</details>

**Comment by Josefpa** [comment]
[https://github.com/flutter-stripe/flutter_stripe/pull/1798](https://github.com/flutter-stripe/flutter_stripe/pull/1798) 

 ;)
