### ISSUE TITLE
CardFormField style dont have take effect on iOS

### ISSUE THREAD

**Issue by fluttermoonger** [flutter-stripe/flutter_stripe#1368]
**Describe the bug**
When using the CardFormField and setting the style such as textColor and placeHolder color. Any color, this is not shown on iOS device. Not in the simulator or on real device. This works on Android. also when switching to darkmode as i have iimplemented the color is dark everywhere and you cant se the input text or the hint text.

**To Reproduce**
1. Add a scaffold with dark background
2. Add the cardformfield on top of the background, lets say using a stack or just center it in a container.
3. Set the textColor to white and placeHolder color to white, The text is still black

**Expected behavior**
When changing the color style i expect the color to change to what i have set.

**Smartphone / tablet**
 - Device: [iPhone 13]
 - OS: [iOS 16, Android 13]
 - Package version: [9.3.0]
 - Flutter version [ latest stable]

**Additional context**
Nothing

**Comment by remonh87** [comment]
On that note I would really recommend for implementing the `paymentSheet` as it is more modern, more customisable and provides a lot of convenience features like localised error handling, animations etc.

**Comment by shahjash1212** [comment]
I have a use case where in I need to store card details and do transactions later on. I have implemented it successfully, using card form field. But because of current issue, it is not looking good in iOS. Can payment sheet be used to do similar things? Because I think it requires intent which I won't have while saving the card.

**Comment by remonh87** [comment]
yes it can if you provide an customer ephermalkey + customer id. See: https://docs.page/flutter-stripe/flutter_stripe/sheet

We recommend using the paymentsheet since it provides far superior user experience and customizability than cardform.

**Comment by PITPL-Maulik-Sinroja** [comment]
The CardFormField style is not applied if the iOS device is in dark mode.

**Stripe CardFormField Code**
<img width="559" alt="Screenshot 2024-01-24 at 5 48 22 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/91668707/258131d9-1059-4127-bc5a-1902f7e513a2">

**Light Mode**
<img width="367" alt="Screenshot 2024-01-24 at 5 47 31 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/91668707/7320a288-5a5a-4a0c-a561-b34dc9764234">

**Dark Mode**
<img width="379" alt="Screenshot 2024-01-24 at 5 42 05 PM" src="https://github.com/flutter-stripe/flutter_stripe/assets/91668707/f09a700e-978a-4ab3-bf3f-486717be375a">

**Comment by shahjash1212** [comment]
> dering if there's a way to show the PaymentSheet UI without these int
 
 try  payment sheet UI it was not working for me But you should try to use it if you have access of paymentIntent

**Comment by koebelt** [comment]
It's been more than a year and this issue is still up. It is really breaking for our usecase since we cannot use the payment sheet in our app when the card field doesn't lead to a payment.

Is there any plans to fix this still or are we obligated to switch to a different library ?

**Comment by jonasbark** [comment]
@koebelt you're welcome to provide the feedback in https://github.com/stripe/stripe-react-native/issues/563 or even better - contribute a fix :)

**Comment by Anish-novelty** [comment]
Has this been fixed yet?

**Comment by koebelt** [comment]
> Has this been fixed yet?

Unfortunately, no.

It's even worse than that. The CardFormField feature is considered deprecated in the iOS native version of the module: [stripe/stripe-ios#1932](https://github.com/stripe/stripe-ios/issues/1932), which is a dependency of this module.
It will, therefore, never be fixed.

They want to push forward the payment modal and deprecate the rest of the mobile features.
