### ISSUE TITLE
Execution failed for task ':stripe_android:verifyReleaseResources'.

### ISSUE THREAD

**Issue by eng-mohamedfarouk** [flutter-stripe/flutter_stripe#1676]
**Describe the bug**
I get an error when I try to generate apk "flutter build apk" as shown

Execution failed for task ':stripe_android:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:3: AAPT: error: resource android:color/system_background_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:4: AAPT: error: resource android:color/system_error_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:5: AAPT: error: resource android:color/system_error_container_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:6: AAPT: error: resource android:color/system_on_surface_light not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:7: AAPT: error: resource android:color/system_primary_light not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:8: AAPT: error: resource android:color/system_surface_light not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:9: AAPT: error: resource android:color/system_on_background_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:10: AAPT: error: resource android:color/system_on_error_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:11: AAPT: error: resource android:color/system_on_error_container_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:12: AAPT: error: resource android:color/system_on_primary_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:13: AAPT: error: resource android:color/system_on_primary_container_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:14: AAPT: error: resource android:color/system_on_secondary_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:15: AAPT: error: resource android:color/system_on_secondary_container_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:16: AAPT: error: resource android:color/system_on_surface_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:17: AAPT: error: resource android:color/system_on_surface_variant_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:18: AAPT: error: resource android:color/system_on_tertiary_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:19: AAPT: error: resource android:color/system_on_tertiary_container_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:20: AAPT: error: resource android:color/system_outline_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:21: AAPT: error: resource android:color/system_outline_variant_dark not found.

     ERROR:/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:22: AAPT: error: resource android:color/system_primary_dark not found.

**Smartphone / tablet**
 - OS: Android 10
 - Package version: 10.1.0
 - Flutter version 3.19.2 

**Additional context**
It work if I run app in emulator with VS Code

**Comment by SivaFullStackDeveloper** [comment]
this needs to fix immediately

**Comment by kothalenehal** [comment]
for now you can downgrade to the earlier working version

> this needs to fix immediately

**Comment by SivaFullStackDeveloper** [comment]
earlier versions are also not working 

PS C:\Users\siva\Desktop\lifeplusclient> flutter build apk

e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.facebook.react.bridge.ReactApplicationContext, unresolved supertypes: ReactContext
Adding -Xextended-compiler-checks argument might provide additional information.

e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformVie
w.kt:10:37 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformVie
w.kt:27:40 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardFormPlatformVie
w.kt:31:59 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt
:8:37 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt
:24:28 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/flutter/stripe/StripeSdkCardPlatformView.kt
:27:33 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldView.kt:14:37
 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldView.kt:34:30
 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldView.kt:59:49
 Unresolved reference: showSoftKeyboard
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldView.kt:65:47
 Unresolved reference: showSoftKeyboard
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldView.kt:69:47
 Unresolved reference: hideSoftKeyboard
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldView.kt:256:7
 Unresolved reference: CardChangedEvent
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldView.kt:361:6
6 Unresolved reference: PostalCodeUtilities
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldView.kt:362:4
5 Unresolved reference: PostalCodeUtilities
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:7:37 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:16:32 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:21:7 Unresolved reference: CardChangedEvent
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:67:49 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:68:26 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:68:74 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:73:22 Variable expected
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:80:26 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:80:78 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:81:22 Variable expected
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:86:26 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:86:78 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFieldViewManager.k
t:90:56 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt:13:37 
Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt:32:29 
Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt:99:26 
Unresolved reference: showSoftKeyboard
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt:106:24
 Unresolved reference: showSoftKeyboard
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt:111:24
 Unresolved reference: hideSoftKeyboard
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt:245:13
 Unresolved reference: CardFormCompleteEvent
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt:258:11
 Unresolved reference: CardFormCompleteEvent
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormView.kt:300:14
 Unresolved reference: PostalCodeUtilities
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:7:37 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:13:32 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:18:7 Unresolved reference: CardFormCompleteEvent
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:64:49 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:65:26 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:65:74 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:70:22 Variable expected
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:77:26 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:77:78 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:78:22 Variable expected
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:83:26 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/CardFormViewManager.kt
:83:78 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/GooglePayButtonView.kt
:7:37 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/GooglePayButtonView.kt
:15:48 Unresolved reference: ThemedReactContext
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/GooglePayButtonView.kt
:46:7 Overload resolution ambiguity:
public constructor GooglePayJsonFactory(context: Context, isJcbEnabled: Boolean = ...) defined in com.stripe.android.GooglePayJsonFactory
public constructor GooglePayJsonFactory(googlePayConfig: GooglePayConfig, isJcbEnabled: Boolean = ...) defined in com.stripe.android.GooglePayJsonFactory     
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:22:46 Unresolved reference: AddressSheetView
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:24:39 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:60:27 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:60:39 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:74:21 Unresolved reference: PaymentSheetException
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:75:27 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:75:39 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:79:7 Unresolved reference: buildPaymentSheetAppearance
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:80:21 Unresolved reference: PaymentSheetAppearanceException
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:81:27 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:81:39 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:86:7 Unresolved reference: AddressSheetView
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:91:50 Type mismatch: inferred type is ReactApplicationContext but Context? was expected
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:100:11 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:100:23 Unresolved reference: PaymentSheetErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:102:11 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:102:23 Unresolved reference: PaymentSheetErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:111:30 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:111:42 Unresolved reference: PaymentSheetErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:115:34 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:115:46 Unresolved reference: PaymentSheetErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:118:34 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:118:46 Unresolved reference: PaymentSheetErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:123:13 Unresolved reference: removeFragment
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:132:28 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:132:55 Unresolved reference: getNativeModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:132:55 Cannot access 'ReactContext' which is a supertype of 'com.facebook.react.bridge.ReactApplicationContext'. Check your module classpath for missing or 
conflicting dependencies
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:132:71 Unresolved reference: StripeSdkModule
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:273:17 Cannot access 'ReactContext' which is a supertype of 'com.facebook.react.bridge.ReactApplicationContext'. Check your module classpath for missing or 
conflicting dependencies
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:273:17 Unresolved reference: currentActivity
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:284:13 Cannot access 'ReactContext' which is a supertype of 'com.facebook.react.bridge.ReactApplicationContext'. Check your module classpath for missing or 
conflicting dependencies
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:284:13 Unresolved reference: currentActivity
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:297:50 Type mismatch: inferred type is ReactApplicationContext but Context? was expected
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:328:27 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:328:39 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:346:14 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:346:26 Unresolved reference: PaymentSheetErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:369:13 Unresolved reference: PaymentSheetException
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:369:13 An annotation argument must be a compile-time constant
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:375:24 Unresolved reference: PaymentSheetException
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:385:18 Unresolved reference: PaymentSheetException
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/PaymentSheetFragment.k
t:396:20 Unresolved reference: PaymentSheetException
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:16:47 Unresolved reference: ReactNativeCustomerAdapter
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:34:33 Unresolved reference: ReactNativeCustomerAdapter
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:72:27 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:72:39 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:76:27 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:76:39 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:81:7 Unresolved reference: buildPaymentSheetAppearance
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:82:21 Unresolved reference: PaymentSheetAppearanceException
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:83:27 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:83:39 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:103:30 Unresolved reference: it
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:125:32 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:125:44 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:132:89 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:170:18 Cannot access 'ReactContext' which is a supertype of 'com.facebook.react.bridge.ReactApplicationContext'. Check your module classpath 
for missing or conflicting dependencies
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:170:18 Unresolved reference: currentActivity
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:182:14 Cannot access 'ReactContext' which is a supertype of 'com.facebook.react.bridge.ReactApplicationContext'. Check your module classpath 
for missing or conflicting dependencies
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:182:14 Unresolved reference: currentActivity
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:199:29 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:199:41 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:206:93 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:211:25 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:211:37 Unresolved reference: CreateTokenErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:220:14 Unresolved reference: createError
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:220:26 Unresolved reference: ErrorType
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:255:8 Unresolved reference: ReactNativeCustomerAdapter
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:266:11 Type mismatch: inferred type is ReactApplicationContext but Context was expected
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:276:11 Type mismatch: inferred type is ReactApplicationContext but Context was expected
e: file:///C:/Users/siva/AppData/Local/Pub/Cache/hosted/pub.dev/stripe_android-9.6.0+2/android/src/main/kotlin/com/reactnativestripesdk/customersheet/Customer
SheetFragment.kt:282:14 Unresolved reference: ReactNativeCustomerAdapter
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 6348 bytes (99.6% reduction). Tree-shaking can be disabled by providing th
e --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 5s

**Comment by remonh87** [comment]
Fixed in stripe_android 10.1.1

**Comment by Okladnoj** [comment]
didn't fixed

` flutter_stripe: 10.1.1`

<details><summary>flutter pub outdated</summary>
<p>

```dart
okji@Mac-mini-Dmytrij lemon_flutter % flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name                      Current  Upgradable  Resolvable  Latest   

direct dependencies:             
animated_custom_dropdown          *1.5.0   *1.5.0      3.0.0       3.0.0    
cloud_functions                   *4.4.2   *4.4.2      *4.6.0      4.6.7    
file_picker                       *5.5.0   *5.5.0      6.2.0       6.2.0    
firebase_core                     *2.17.0  *2.17.0     *2.24.2     2.26.0   
firebase_core_platform_interface  *4.8.0   *4.8.0      5.0.0       5.0.0    
firebase_dynamic_links            *5.3.7   *5.3.7      *5.4.8      5.4.16   
firebase_messaging                *14.6.9  *14.6.9     *14.7.10    14.7.18  
flutter_local_notifications       *15.1.3  *15.1.3     16.3.3      16.3.3   
info_popup                        *3.0.6   *3.0.6      4.3.1       4.3.1    
intl                              *0.18.1  *0.18.1     *0.18.1     0.19.0   
table_calendar                    *3.0.9   *3.0.9      *3.0.9      3.1.0    

dev_dependencies:                
flutter_lints                     *2.0.3   *2.0.3      3.0.1       3.0.1    
flutter_native_splash             *2.3.10  *2.3.10     *2.3.10     2.3.13   

10  dependencies are constrained to versions that are older than a resolvable version.
To update these dependencies, edit pubspec.yaml, or run `flutter pub upgrade --major-versions`.
okji@Mac-mini-Dmytrij lemon_flutter % 

``` 

</p>
</details> 


<details><summary>Logs</summary>
<p>

 *  Executing task: ./scripts/build_android.sh 

Starting build...
Building for dev mode based on the Git branch 'dev'...
Select build type: 1 for APK, 2 for App Bundle [default: 1]
Enter choice (1/2): 
Building in dev mode as apk...
Cleaning Xcode workspace...                                         3,6s
Deleting build...                                                    9ms
Deleting .dart_tool...                                               0ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            1ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Resolving dependencies... 
  _fe_analyzer_shared 61.0.0 (67.0.0 available)
  _flutterfire_internals 1.3.7 (1.3.24 available)
  analyzer 5.13.0 (6.4.1 available)
  animated_custom_dropdown 1.5.0 (3.0.0 available)
  cloud_functions 4.4.2 (4.6.7 available)
  cloud_functions_platform_interface 5.5.2 (5.5.18 available)
  cloud_functions_web 4.6.2 (4.7.1 available)
  csslib 0.17.3 (1.0.0 available)
  dart_style 2.3.2 (2.3.6 available)
  file_picker 5.5.0 (6.2.0 available)
  firebase_core 2.17.0 (2.26.0 available)
  firebase_core_platform_interface 4.8.0 (5.0.0 available)
  firebase_core_web 2.8.0 (2.11.5 available)
  firebase_dynamic_links 5.3.7 (5.4.16 available)
  firebase_dynamic_links_platform_interface 0.2.6+7 (0.2.6+24 available)
  firebase_messaging 14.6.9 (14.7.18 available)
  firebase_messaging_platform_interface 4.5.8 (4.5.26 available)
  firebase_messaging_web 3.5.8 (3.6.7 available)
  flutter_lints 2.0.3 (3.0.1 available)
  flutter_local_notifications 15.1.3 (16.3.3 available)
  flutter_native_splash 2.3.10 (2.3.13 available)
  info_popup 3.0.6 (4.3.1 available)
  intl 0.18.1 (0.19.0 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.4 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.3 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
  meta 1.11.0 (1.12.0 available)
  stripe_android 10.1.0 (10.1.1 available)
  table_calendar 3.0.9 (3.1.0 available)
  test_api 0.6.1 (0.7.0 available)
  vm_service 13.0.0 (14.1.0 available)
Got dependencies!
33 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
flutter build apk --release --dart-define=prod=false

You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/okji/.pub-cache/hosted/pub.dev/firebase_messaging-14.6.9/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1988 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Note: /Users/okji/.pub-cache/hosted/pub.dev/stripe_android-10.1.0/android/src/main/kotlin/com/facebook/react/uimanager/DisplayMetricsHolder.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_android:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:3: AAPT: error: resource android:color/system_background_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:4: AAPT: error: resource android:color/system_error_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:5: AAPT: error: resource android:color/system_error_container_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:6: AAPT: error: resource android:color/system_on_surface_light not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:7: AAPT: error: resource android:color/system_primary_light not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:8: AAPT: error: resource android:color/system_surface_light not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:9: AAPT: error: resource android:color/system_on_background_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:10: AAPT: error: resource android:color/system_on_error_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:11: AAPT: error: resource android:color/system_on_error_container_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:12: AAPT: error: resource android:color/system_on_primary_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:13: AAPT: error: resource android:color/system_on_primary_container_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:14: AAPT: error: resource android:color/system_on_secondary_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:15: AAPT: error: resource android:color/system_on_secondary_container_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:16: AAPT: error: resource android:color/system_on_surface_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:17: AAPT: error: resource android:color/system_on_surface_variant_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:18: AAPT: error: resource android:color/system_on_tertiary_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:19: AAPT: error: resource android:color/system_on_tertiary_container_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:20: AAPT: error: resource android:color/system_outline_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:21: AAPT: error: resource android:color/system_outline_variant_dark not found.

     ERROR: /Users/okji/work/flutter/lemon_flutter/build/stripe_android/intermediates/merged_res/release/values-v34/values-v34.xml:22: AAPT: error: resource android:color/system_primary_dark not found.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 9s
Running Gradle task 'assembleRelease'...                          130,5s
Gradle task assembleRelease failed with exit code 1
Build completed. The apk is ready for deployment.
 *  Terminal will be reused by tasks, press any key to close it. 


</p>
</details>

**Comment by Kalyan-Halder** [comment]
use flutter_stripe: 10.1.1 ,
flutter pub upgrade
flutter pub get
flutter clean
flutter build apk
this worked for me

**Comment by Aptul9** [comment]
error still showing up for me after the upgrade to the latest version

**Comment by SivaFullStackDeveloper** [comment]
hey change the your compile sdk to 34 will work cool

**Comment by eng-mohamedfarouk** [comment]
after update flutter to latest version and use flutter_stripe: 10.1.1 , it work cool now
