### ISSUE TITLE
🐞 Issue with applySettings() for Stripe Account ID on web

### ISSUE THREAD

**Issue by Josefpa** [flutter-stripe/flutter_stripe#1785]
#### **Describe the Bug**
Using `await Stripe.instance.applySettings();` to update an `accountId` shows the updated `accountId` when printed, but it does not apply to the `confirmPayment()` method. This occurs when attempting to update `Stripe.stripeAccountId` within the app, such as on the payment page.

#### **To Reproduce**
1. Initialize a Stripe instance within `main.dart`, setting the Stripe publisher key (no account ID set).
2. Have a page within your app that initializes Stripe but adds the Stripe connect ID:
    ```dart
    Stripe.stripeAccountId = id;
    await Stripe.instance.applySettings();
    ```
3. Check out with `Stripe.instance.confirmPayment()` and print to the console the account ID.

   - It will show the correct account ID.
   - The payment will fail, stating the intent is incorrect for the false account (it will use your main account instead of the accountID).

   Note: On iOS and Android, it goes through successfully.

If two `await Stripe.instance.applySettings();` calls take place, the second one applies but does not update the actual values unless something that should reinitialize the elements is missing.

#### **Expected Behavior**
For the update to go through since the Stripe account ID is dynamic in Stripe Connect scenarios.

**Comment by EdHourani** [comment]
https://github.com/flutter-stripe/flutter_stripe/issues/1042

**Comment by Josefpa** [comment]
@EdHourani you might be right its seems the same issue, any idea where the issue is caused, might be able to fix it?

**Comment by EdHourani** [comment]
yea, line 59 of this file should work but doesn't 
https://github.com/flutter-stripe/flutter_stripe/blob/main/packages/stripe_web/lib/src/web_stripe.dart

not very happy with my work around, but what i did was maintain a map of stripe_js.Stripe instances per accountId instead of the one on line 23 of the same file
not the best approach, but got the app through the door

**Comment by Josefpa** [comment]
I may have found a fix, still needs to be approved but it basically checks if the current `StripeAccountID `is the same and if not creates a new one  
[](https://github.com/flutter-stripe/flutter_stripe/pull/1798)

Fixed code here: 
```
  @override
  Future<void> initialise({
    required String publishableKey,
    String? stripeAccountId,
    ThreeDSecureConfigurationParams? threeDSecureParams,
    String? merchantIdentifier,
    String? urlScheme,
    bool? setReturnUrlSchemeOnAndroid,
  }) async {
    this._urlScheme = urlScheme;
    if (__stripe != null) {
      __stripe!.stripeAccount = stripeAccountId;
      print('setOriginally');
      print('This is the new Id$stripeAccountId');
      return;
    }

    await stripe_js.loadStripe();
    var stripeOption = stripe_js.StripeOptions();  // Changed from final to var
    if (stripeAccountId != null) {
      stripeOption.stripeAccount = stripeAccountId;
    }
    __stripe = stripe_js.Stripe(publishableKey, stripeOption);
  }
```

**Comment by Josefpa** [comment]
[https://github.com/flutter-stripe/flutter_stripe/pull/1798](https://github.com/flutter-stripe/flutter_stripe/pull/1798)

**Comment by Josefpa** [comment]
Check [Version 10.2.0](https://pub.dev/packages/flutter_stripe/changelog#1020) 😉

**Comment by appeventic** [comment]
@Josefpa I'm using `flutter_stripe: ^10.2.0` but still can't set the external account ID, confirm payment intent giving me this error when we're testing over web, from native app works fine. Could you please help how I can set external account id for web?

```
"message": "No such PaymentMethod: 'sxsdsd'; OAuth key or Stripe-Account header was used but API request was provided with a platform-owned payment method ID. Please ensure that the provided payment method matches the specified account."
"type": "invalid_request_error"
```

**Comment by saadrasool99** [comment]
Hifolks. I was stuck with the same issue on stripe payment with web app in flutter. after trying multiple solutions finally it works for me. just add flutter_stripe_web package with flutter_stripe package this will solve your problem.

**Comment by appeventic** [comment]
@saadrasool99 @EdHourani @Josefpa @ignatz can someone please help, we're really blocked with this issue. Here are the high level steps we're performing for flutter web payment -
1. create payment intent in the backend with `stripeAccount`
2. On the client side change stripe accountId using `Stripe.stripeAccountId`
3. On client side confirm payment using `await Stripe.instance.confirmPayment` with clientSecret received from step1.

I'm getting this error - _IntegrationError: Please use the same instance of `Stripe` you used to create this Element to create your Source or Token._

<img width="1503" alt="Screenshot 2024-09-30 at 9 27 13 PM" src="https://github.com/user-attachments/assets/1f4c4f60-325a-4b00-aff9-91a1755ed575">

Here are the versions we're using -
```
  flutter_stripe: ^11.1.0
  flutter_stripe_web: ^6.1.0
```

**Comment by Josefpa** [comment]
@appeventic you need to call the stripe set account ID only once; this should be i guess when the checkout page loads... after that dont call it again unless you change it as if you do you will have to stripe instnaces running with two seperate accounts ids (even tho they are the same)

**Comment by Josefpa** [comment]
@saadrasool99 you are correct; I just run `flutter_stripe: ^11.2.0 ` or the newest verison

and the rest can be any

```
 stripe_platform_interface: any
  stripe_android: any
  stripe_ios: any
  flutter_stripe_web: any
  stripe_js: any
```
  
  Sorry about the delay
