### ISSUE TITLE
Apple pay not showing a payment sheet on production mode

### ISSUE THREAD

**Issue by maziarit** [flutter-stripe/flutter_stripe#262]
**Describe the bug**
My application fully work when on debug mode on the IOS simulator but when upload the IOS app on App Store connect payment sheet not showing

**My code**

> await Stripe.instance.presentApplePay(
          ApplePayPresentParams(
            cartItems: [
              ApplePayCartSummaryItem(
                label: allTranslations.text(selectedPlan["planType"]["name"]),
                amount: (paymentIntent["amount"] / 100).toString(),
              ),
            ],
            country: 'gb',
            currency: 'gbp',
          ),
        );
        await Stripe.instance
            .confirmApplePayPayment(paymentIntent["client_secret"]);

**Smartphone**
 - Device: [iPhone 10 pro]
 - OS: [e.g. iOS 14.7.1]
 - Package version: [flutter_stripe: ^1.2.0]
 - Flutter version [e.g. 2.2.3.]

**Comment by jamesblasco** [comment]
Please, confirm that you have implemented the following steps needed to enable Apple Pay on production:

https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay

**Comment by vanfresh** [comment]
@jamesblasco I am testing on production but with stripe test credentials and I can confirm that I have implemented the steps.  The `isApplePaySupported` is returning true, but it doesn't present the payment sheet.  If I turn off apple pay support, the payment sheet displays correctly.

**Comment by hai199580** [comment]
> Please, confirm that you have implemented the following steps needed to enable Apple Pay on production:
> 
> https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay

Same issue, i implemented that, but when run

**Comment by CalmAndCoDe** [comment]
Hi, i have the same issue, recently uploaded my app for appstore review and it got rejected, i've completed all steps for apply pay including merchant id, payment processing certificate and apple pay capability in xcode, everything works fine in test environment but for production or testflight it doesn't shows the payment sheet.

**Comment by ymerdrengene** [comment]
Any news on this issue?

**Comment by hai199580** [comment]
@ymerdrengene try to add the card to Wallets app before. Check the value of :

Stripe.instance.isApplePaySupported 

If you have not added card, this value will be false, and the payment sheet cannot show.

Sorry for my bad English, hope it help

**Comment by ymerdrengene** [comment]
Hello @hai199580 I have tried that too, but it still doesn't show the paymentsheet. @maziarit did you manage to fix this?

**Comment by remonh87** [comment]
Three attention points for going to production:
- make sure that you use the production keys on both the server as in the app 
- check that `Stripe.instance.isApplePaySupported ` is `true`
- make sure that you set the correct merchant identifier.

https://github.com/flutter-stripe/flutter_stripe/blob/d91eda2a6b86899791903b6cee834eec54d43bdd/packages/stripe/lib/src/stripe.dart#L77

I successfully went to production with the paymentsheet and Apple Pay with this library.

**Comment by yrming** [comment]
> Hi, i have the same issue, recently uploaded my app for appstore review and it got rejected, i've completed all steps for apple pay including merchant id, payment processing certificate and apple pay capability in xcode, everything works fine in test environment but for production or testflight it doesn't shows the payment sheet.

@olivergibson Hi, I have the same problem, did you solve it?

**Comment by MomenA7med** [comment]
> @jamesblasco
> 
> > Please, confirm that you have implemented the following steps needed to enable Apple Pay on production:
> > https://developer.apple.com/documentation/passkit/apple_pay/setting_up_apple_pay
> 
> Same issue, i implemented that, but when run presentApplePay method, it throw exception
> 
> > PlatformException(Failed, Payment not completed, null, null)
> 
> ```
> try {
>       await Stripe.instance.presentApplePay(
>         ApplePayPresentParams(
>           cartItems: [
>             ApplePayCartSummaryItem(
>               label:  "1000P",
>               amount: "1000Y",
>             ),
>           ],
>           country: 'jp',
>           currency: 'jpy',
>         ),
>       );
> 
>       await Stripe.instance.confirmApplePayPayment(paymentIntent.clientSecret ?? '');
> 
>       ......
>     } catch (e) {
>       // Exception
>     }
> ```

@hai199580 
Did you find a solution ?
