### ISSUE TITLE
Stripe.instance.presentGooglePay throws exception even tho Google Pay is enabled in my device

### ISSUE THREAD

**Issue by t00nami** [flutter-stripe/flutter_stripe#340]
**Describe the bug**
New Google Pay feature without pay plugin not working.

**To Reproduce**
1. Download and run Google Pay example
2. Add a real credit card to your Google Pay
3. Tap the Google Pay button.
4. Stripe payment intent created succesfully
4. Exception at Stripe.instance.presentGooglePay

`StripeException(error: LocalizedErrorMessage(code: FailureCode.Failed, localizedMessage: presentForPaymentIntent() may only be called when Google Pay is available on this device., message: presentForPaymentIntent() may only be called when Google Pay is available on this device., stripeErrorCode: null, declineCode: null, type: null))`

**Expected behavior**
Stripe.instance.presentGooglePay should pop up Google Pay view

**Smartphone / tablet**
 - Real Device: Pocophone F1
 - Emulator Device: Pixel 4 API 28
 - OS: Android 10
 - Package version: 1.3.0
 - Flutter version: Flutter 2.5.0 • channel stable

**Additional context**

Code:
```
      final paymentIntent = await createPaymentIntent(amount, currency, description, secret);
      final clientSecret = paymentIntent!['client_secret'];

      await Stripe.instance.initGooglePay(GooglePayInitParams(testEnv: true, merchantName: "Merchant Name Test", countryCode: 'es'));

      await Stripe.instance.presentGooglePay(
        PresentGooglePayParams(clientSecret: clientSecret),
      );
```

**Comment by remonh87** [comment]
There is a bug on the native Stripe SDK which is fixed now: https://github.com/stripe/stripe-react-native/pull/546/files. We will integrate this in the next version

**Comment by tijnar** [comment]
Got the same error. Is a new version update coming soon or do we need to wait for some more weeks?

**Comment by tijnar** [comment]
> There is a bug on the native Stripe SDK which is fixed now: https://github.com/stripe/stripe-react-native/pull/546/files. We will integrate this in the next version

I am stuck in this issue for a very long time. Is there any workaround before the next version?

**Comment by Michele-x98** [comment]
I know, but with the same code as above and with the version 1.3.0 it still doesn't work for me.

**Comment by remonh87** [comment]
it should be fixed with version 2.0.0

**Comment by rockz1999** [comment]
> it should be fixed with version 2.0.0

Still Facing the same issue in version 2.0.1
